// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfPQyVVpeNM4N9578Ij60darRi1CsHkg',
    appId: '1:783134278062:web:9a7e465624b1b05768483f',
    messagingSenderId: '783134278062',
    projectId: 'flutter-assignment-6-1cc24',
    authDomain: 'flutter-assignment-6-1cc24.firebaseapp.com',
    storageBucket: 'flutter-assignment-6-1cc24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZlvA8Mzba6unFIRPaaR6bc3ep2JU5i8',
    appId: '1:783134278062:android:bd38dd3447f1e94868483f',
    messagingSenderId: '783134278062',
    projectId: 'flutter-assignment-6-1cc24',
    storageBucket: 'flutter-assignment-6-1cc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrU1yQdCHalQbp-X66bcSJ3OdU367jZ4',
    appId: '1:783134278062:ios:6790bc2e26aacdb568483f',
    messagingSenderId: '783134278062',
    projectId: 'flutter-assignment-6-1cc24',
    storageBucket: 'flutter-assignment-6-1cc24.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignment6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfPQyVVpeNM4N9578Ij60darRi1CsHkg',
    appId: '1:783134278062:web:92660c7ac93f745768483f',
    messagingSenderId: '783134278062',
    projectId: 'flutter-assignment-6-1cc24',
    authDomain: 'flutter-assignment-6-1cc24.firebaseapp.com',
    storageBucket: 'flutter-assignment-6-1cc24.firebasestorage.app',
  );
}
